# Generated by Django 2.1.3 on 2018-11-07 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0001_initial'),
        ('organ', '0002_delete_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_organs',
            fields=[
                ('organ_id', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('blood', models.CharField(default=None, max_length=4)),
                ('received_date', models.CharField(default=None, max_length=15)),
                ('donated_date', models.CharField(default=None, max_length=15)),
                ('available_place', models.CharField(default=None, max_length=100)),
                ('donated_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.donor')),
                ('received_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_organ_recieved_from', to='donation.donor')),
            ],
        ),
        migrations.CreateModel(
            name='eyes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unfit', models.CharField(default=None, max_length=200, null=True)),
                ('organ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.all_organs')),
            ],
        ),
        migrations.CreateModel(
            name='kidney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(default=None, max_length=100, null=True)),
                ('cadaver', models.CharField(default=None, max_length=100)),
                ('organ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.all_organs')),
            ],
        ),
        migrations.CreateModel(
            name='liver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viral_testing', models.CharField(default=None, max_length=200, null=True)),
                ('organ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.all_organs')),
            ],
        ),
    ]
